## Common Imports

In [48]:
import pandas as pd
import numpy as np

## Load data

In [49]:
eval_data_formatted = pd.read_pickle('pickle_files/eval_data_formatted.pickle') #raw evaluation data for referencing
eval_data_formatted['Tweet ID'] = eval_data_formatted['Tweet ID'].astype(str) #set tweet id type as string
class_results = pd.read_pickle('results/classifier_results.pickle') #tweet by tweet classifications per model
metrics = pd.read_pickle('results/classifications.pickle') #overall metrics per model
actual = pd.read_pickle('features/df_tweet_eval.pickle') #get the actual classifications per tweet
actual_class = actual.loc[:,['tweet_id','class_column']] #get the actual classifications per tweet

In [50]:
class_results['desc'] = class_results['model']+ ' model using '+class_results['file']
class_results_pivot = class_results.pivot(index='tweet_id',columns='desc',values='pred').reset_index()

## Counts of positives and negatives per tweet

In [51]:
df_check = class_results_pivot.copy() #copy the detailed results
model_counts = len(df_check.columns)-1 #count the total number of models in df_check
df_check['count_positive'] = df_check.sum(axis=1) #create a column counting the number of positives
df_check = pd.merge(df_check, actual_class, on='tweet_id') #merge the actual class for each tweet
df_check = df_check.loc[:,['tweet_id','count_positive','class_column']]   #create dataframe with the actual class and the
df_check['count_negative'] = model_counts - df_check['count_positive']    #counts of positive and negative predictions per tweet

In [52]:
t_id = [] #array to hold tweet ids
tweet = [] #array to hold tweet texts
desc = [] #classifier and feature combo
count = [] #number of classifier/feature combos classifying correctly
t = [] #the type of correct classification

for n in range(0,5): #n is the number of classifier/feature combos that got the right classification
    tweet_list = df_check[(df_check.count_negative==n)&(df_check.class_column==0)].tweet_id #negative class 
    if n==0:                                                                                #tweets with n negative 
        if (len(tweet_list)>0): #if there are tweets without correct classification         #correct classifiers
            t_id = np.append(t_id,tweet_list) #append tweet ids
            tweet = np.append(tweet,eval_data_formatted[eval_data_formatted['Tweet ID'].isin(tweet_list)].Tweet) #append tweet text
            desc = np.append(desc,np.repeat('no models',len(tweet_list))) #append classifier and feature combo description
            count = np.append(count,np.repeat(n,len(tweet_list))) #append number of classifier/feature combos classifying correctly
            t = np.append(t,np.repeat('tn',len(tweet_list))) #append the type of correct classification
    else:
        for tw_id in tweet_list: #go through each tweet id
            t_id = np.append(t_id,np.repeat(tw_id,n)) #append tweet id
            tweet = np.append(tweet,np.repeat(eval_data_formatted[eval_data_formatted['Tweet ID']==tw_id].Tweet,n)) #tweet text
            desc = np.append(desc,class_results[(class_results.pred==0)&(class_results.tweet_id==tw_id)].desc) #classifier/feature combo
            count = np.append(count,np.repeat(n,n)) #append number of classifier/feature combos classifying correctly
            t = np.append(t,np.repeat('tn',n)) #append the type of correct classification
            
            
    tweet_list = df_check[(df_check.count_positive==n)&(df_check.class_column==1)].tweet_id #positive class
    if n==0:                                                                                #tweets with n negative 
        if (len(tweet_list)>0): #if there are tweets without correct classification         #correct classifiers
            t_id = np.append(t_id,tweet_list) #append tweet ids
            tweet = np.append(tweet,eval_data_formatted[eval_data_formatted['Tweet ID'].isin(tweet_list)].Tweet) #append tweet text
            desc = np.append(desc,np.repeat('no models',len(tweet_list))) #append classifier and feature combo description
            count = np.append(count,np.repeat(n,len(tweet_list))) #append number of classifier/feature combos classifying correctly
            t = np.append(t,np.repeat('tp',len(tweet_list))) #append the type of correct classification
    else:
        for tw_id in tweet_list: #go through each tweet id
            t_id = np.append(t_id,np.repeat(tw_id,n)) #append tweet id
            tweet = np.append(tweet,np.repeat(eval_data_formatted[eval_data_formatted['Tweet ID']==tw_id].Tweet,n)) #tweet text
            desc = np.append(desc,class_results[(class_results.pred==1)&(class_results.tweet_id==tw_id)].desc) #classifier/feature combo
            count = np.append(count,np.repeat(n,n)) #append number of classifier/feature combos classifying correctly
            t = np.append(t,np.repeat('tp',n)) #append the type of correct classification            
            
            
print(len(t_id))
print(len(tweet))
print(len(desc))
print(len(count))
print(len(t))

32
32
32
32
32

In [53]:

#Set the display.max_colwidth option to -1:

pd.options.display.max_colwidth = 280
df = pd.DataFrame({'t_id':t_id,'tweet':tweet,'desc':desc,'count':count,'t':t})
df

,count,desc,t,t_id,tweet
0,0.0,no models,tn,1153765869761302529,Nicola sturgeon has a face I would punch
1,0.0,no models,tp,861994773934206976,"If you had a gun and one bullet with Donald Trump to the left and Nicolas Sturgeon to the right, which one gets it?"
2,1.0,lr model using features/df_tweet_eval.pickle,tp,839521881493553152,"How to recognise a slut: ""check Nicola Sturgeon as example, that's exactly the behaviour of the slut next door trying to spli…"
3,1.0,lr model using features/df_tweetbio_eval.pickle,tp,843217597999038469,not sure - sturgeon appears to be going mad & introducing Sharia banking. the SNP has been bought by paki…
4,1.0,dt model using features/df_tweet_eval.pickle,tp,888118576573325312,This may be a blessing in disguise. I'm enjoying all this Sturgeon news in the mean time. The Scottish dwarf an…
5,1.0,lr model using features/df_tweet_eval.pickle,tp,903023685237448707,Sturgeon has no interest in Scotland's children because she has no children of her own. Her womb is as barren as...
6,2.0,dt model using features/df_tweet_tfidf_eval.pickle,tn,1154792142348410880,A just wish Nicola sturgeon would shut the fuck up
7,2.0,dt model using features/df_tweet_tf_eval.pickle,tn,1154792142348410880,A just wish Nicola sturgeon would shut the fuck up
8,2.0,dt model using features/df_tweetbio_tfidf_eval.pickle,tp,895011275800969217,"Scotland SNP first minister Nicola Sturgeon now using miscarriage story for votes, can she stoop no lower?"
9,2.0,dt model using features/df_tweetbio_tf_eval.pickle,tp,895011275800969217,"Scotland SNP first minister Nicola Sturgeon now using miscarriage story for votes, can she stoop no lower?"
10,2.0,dt model using features/df_tweet_tfidf_eval.pickle,tp,896656916738453504,"""Make the lie big,\nmake it simple,\nkeep saying it,\nand eventually they will believe it.""\nA̶d̶o̶l̶f̶ ̶H̶i̶t̶l̶e̶r̶\nNicola Sturg…"
11,2.0,dt model using features/df_tweet_tf_eval.pickle,tp,896656916738453504,"""Make the lie big,\nmake it simple,\nkeep saying it,\nand eventually they will believe it.""\nA̶d̶o̶l̶f̶ ̶H̶i̶t̶l̶e̶r̶\nNicola Sturg…"
12,2.0,dt model using features/df_tweet_tfidf_eval.pickle,tp,910247211031781376,"As Andrew Neil steps down from his Sunday Politics role, a reminder of the time he called Sturgeon a 'Tipsy Scotch Tart'. htt…"
13,2.0,dt model using features/df_tweet_tf_eval.pickle,tp,910247211031781376,"As Andrew Neil steps down from his Sunday Politics role, a reminder of the time he called Sturgeon a 'Tipsy Scotch Tart'. htt…"
14,3.0,dt model using features/df_tweet_tfidf_eval.pickle,tp,886137229004943361,big enough to bury sturgeon in lol
15,3.0,dt model using features/df_tweet_tf_eval.pickle,tp,886137229004943361,big enough to bury sturgeon in lol
16,3.0,svm model using features/df_tweet_eval.pickle,tp,886137229004943361,big enough to bury sturgeon in lol
17,3.0,lr model using features/df_tweet_eval.pickle,tp,894618728435994625,Me &amp; reckon Sturgeon is a tranny so therefore mentally ill.Scotland is no more a country than Lanna is.
18,3.0,lr model using features/df_tweetbio_eval.pickle,tp,894618728435994625,Me &amp; reckon Sturgeon is a tranny so therefore mentally ill.Scotland is no more a country than Lanna is.
19,3.0,svm model using features/df_tweet_eval.pickle,tp,894618728435994625,Me &amp; reckon Sturgeon is a tranny so therefore mentally ill.Scotland is no more a country than Lanna is.
20,4.0,lr model using features/df_tweetbio_eval.pickle,tp,839632199636893696,"I know this may be harsh,but has lied about so many things in the last 2 yrs should we believe her about the mi…"
21,4.0,dt model using features/df_tweet_tfidf_eval.pickle,tp,839632199636893696,"I know this may be harsh,but has lied about so many things in the last 2 yrs should we believe her about the mi…"
22,4.0,dt model using features/df_tweet_tf_eval.pickle,tp,839632199636893696,"I know this may be harsh,but has lied about so many things in the last 2 yrs should we believe her about the mi…"
23,4.0,dt model using features/df_tweetbio_eval.pickle,tp,839632199636893696,"I know this may be harsh,but has lied about so many things in the last 2 yrs should we believe her about the mi…"
24,4.0,dt model using features/df_tweet_tfidf_eval.pickle,tp,842488032825675776,Nicola Sturgeon.The Queen has had your bed made up in the tower.
25,4.0,dt model using features/df_tweet_tf_eval.pickle,tp,842488032825675776,Nicola Sturgeon.The Queen has had your bed made up in the tower.
26,4.0,dt model using features/df_tweetbio_tfidf_eval.pickle,tp,842488032825675776,Nicola Sturgeon.The Queen has had your bed made up in the tower.
27,4.0,dt model using features/df_tweetbio_tf_eval.pickle,tp,842488032825675776,Nicola Sturgeon.The Queen has had your bed made up in the tower.
28,4.0,lr model using features/df_tweetbio_tfidf_eval.pickle,tp,888117813142933504,"You missed something in your eloquent description of Sturgeon... ""lazy FAT HUGE ENORMOUS mendacious arse"""
29,4.0,lr model using features/df_tweetbio_tf_eval.pickle,tp,888117813142933504,"You missed something in your eloquent description of Sturgeon... ""lazy FAT HUGE ENORMOUS mendacious arse"""
30,4.0,lr model using features/df_tweetbio_eval.pickle,tp,888117813142933504,"You missed something in your eloquent description of Sturgeon... ""lazy FAT HUGE ENORMOUS mendacious arse"""
31,4.0,dt model using features/df_tweet_eval.pickle,tp,888117813142933504,"You missed something in your eloquent description of Sturgeon... ""lazy FAT HUGE ENORMOUS mendacious arse"""

In [55]:
#negative class tweets where all classifiers were correct
df_check[(df_check.count_negative==model_counts)&(df_check.class_column==0)].tweet_id

0      1146950933437399040
2      1147011915782217729
5      1147068052124721153
7      1147105421477519360
9      1147151158869291009
10     1147183701471715334
11     1147187636274159619
12     1147203277680992257
13     1147208820780949506
15     1147213985332310016
19     1147281943442145285
20     1147290184381325312
21     1147376927562297344
22     1147391597946032128
23     1147400639913353216
24     1147425298465599488
25     1147428283958661120
26     1147436203521843200
27     1147440752320032769
28     1147443502516723714
29     1147443835854905344
30     1147476689351405571
31     1147481872915673089
32     1147496710706536455
33     1147526639456333831
34     1147557232885817345
35     1147571451647733760
36     1147593370614685697
37     1147600128582279168
38     1147601877841960960
              ...
794    1157431335151132672
795    1157459954317631488
796    1157548075755458560
797    1157574705827733504
798    1157575328077877248
799    1157581346560184320
800    1157600016384561154
804    1157679964965285888
805    1157682570479452160
806    1157690938375979008
808    1157698496511795200
809    1157731488496005120
810    1157731626308263938
812    1157751895525601280
813    1157765828974194689
814    1157775726105505792
815    1157786826486222851
817    1157811884684382216
818    1157872039987830789
819    1157872246909800449
820    1157907761801416704
822    1157941369828257792
823    1157942918751105024
824    1157970208595861504
825    1157974240106352640
826    1157974283911610368
827    1157974330657169408
828    1157974611818102784
829    1157974810833686529
830    1157974989318033415
Name: tweet_id, Length: 628, dtype: object

In [56]:
#positive class tweets where all classifiers were correct
df_check[(df_check.count_positive==model_counts)&(df_check.class_column==1)].tweet_id

831     839518607986028546
835     839518903969660928
837     839519889475919873
840     839520742316310534
841     839520775027699713
844     839521392160829440
854     839772018002264064
856     839779531166781440
858     839806920273899521
860     839806979413590016
865     839902064465567744
868     840250806536417284
875     841450686340558848
876     841452033232248833
878     842335890127114241
883     842483329576435712
889     842785030787289089
894     843135477645524992
896     843202747327565824
905     843402105633357824
913     869579614493999106
915     869583224577642496
919     885612667490230272
920     885613044558114818
925     885621747785105408
947     888673644951502849
948     889528968084418561
954     894616196473126912
977     896854052042100736
978     897362210825154560
982     902242182064517120
984     902243642894680065
986     902473672618905600
987     902473790403248128
992     902479525300326400
999     903361835130396672
1006    906258064092876801
1007    906258171336982529
1008    906258533724942336
1009    906258689958477835
1010    906258763673456642
1013    906431625009025024
1014    910247040894013440
Name: tweet_id, dtype: object

In [ ]:
eval_data_formatted.columns

In [ ]:
df_check[(df_check.count_positive==1)&(df_check.class_column==1)].tweet_id